version: "3.1"
services:
  nginx-en:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: laraws/design-patterns-php-doc:latest
    container_name: design-nginx
    restart: unless-stopped
    ports:
      - "8081:80"

  nginx-cn:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    image: laraws/design-patterns-php-doc:cn
    container_name: design-zh_CN
    restart: unless-stopped
    ports:
      - "8083:80"
