version: "3.1"
services:
  design-nginx:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: laraws/design-patterns-php-doc:latest
    container_name: design-nginx
    ports:
      - "8081:80"
